name: dotnet package

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

defaults:
  run:
    working-directory: './src/BPCalculator'
    
env:    
  AZURE_WEBAPP_NAME: BloodPressureApp
  AZURE_WEBAPP_PACKAGE_PATH: './published'
  NETCORE_VERSION: '5.0.x'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Check Vulnerabilities
        run:  dotnet list package --vulnerable
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish --no-build -c Release -o  ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: 'Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_SECRET_PROFILE }}
          package: ${{ env.AZUREAPPSERVICE_PUBLISHPROFILE_8E960ACC173B4074BB67B942E12EB140 }}
